projeto-spider/labes-2019

seeds/students.js

A única coisa que aconteceu aqui foi a criação da seed dos estudantes e o banco tá quebrado.

Semente dos estudantes criada

---

components/importStudents.vue
components/searchInput.vue
layouts/default.vue
layouts/empty.vue
middleware/auth.js
pages/allStudents.vue
pages/login.vue

Foi inicializado sistema de login para o front-end do sistema, 
Adicionado button para alunos totais.
Iniciado tela de import.

M06 US02 a 05  Adicionar alunos totais a ferramenta Front-end.

---

server/router.js

Evita criar múltiplos middlewares

Reutiliza middleware de body parsing no router.js

---

components/searchInput.vue
components/studentComboBox.vue
pages/allStudents.vue
server/router.js
test/server/controllers/auth.spec.js

Hotfix para ordenação e paginação 

---

components/studentComboBox.vue

Adição de campo de email editável ao combo box.

---

components/studentComboBox.vue

bug da issue #64, que evita o erro quando o usuário desiste de fazer upload de arquivo a partir da segunda tentativa na mesma tela.

bug da issue #64, que evita o erro quando o usuário desiste de fazer upload de arquivo no comboBox pela segunda vez.

---

test/server/controllers/documents.spec.js

Em atendimento a issue #65 
Closes #65

Cria teste unitário para recuperação de documento após edição de estudante

---

migrations/20190527115705_subjects.js
seeds/subjects.js
server/controllers/subjects/Create.js
server/controllers/subjects/Delete.js
server/controllers/subjects/List.js
server/controllers/subjects/Show.js
server/controllers/subjects/Update.js
server/controllers/subjects/index.js
server/models/Subject.js
server/router.js
test/server/controllers/subjects.spec.js
test/server/models/subjects.spec.js

Falta criar teste unitário
Problema na função de atualizar matérias (o id precisa estar no body e na query). Soluções são bem vindas.

Crud Materias Back End Daniel

---

components/studentComboBox.vue

@jairofilho79 
Esqueceu de incluir este commit na PR anterior

fix do fix do Truncamento de CRG

---

components/searchInput.vue
layouts/default.vue
pages/formingStudents.vue

Closes PR: #108
Atende: Issue #67.
Fix #67
Nova PR aberta para correção de linha de tempo

Meta 08 - Página de formandos

---

server/controllers/students/Update.js
test/server/controllers/students.spec.js

Atende: issue #125 
Adaptado conforme orientação.
Nada a ser adaptado no front nem na wiki.

Corrige atualização de dados do estudante [Back]

---

server/controllers/students/List.js
test/server/controllers/students.spec.js

Atendimento a issue #118 (Closes #118).
Alterada query para filtro do e-mail utilizando LIKE e inclusão dos testes unitários.

Corrige o filtro de e-mail

---

components/exportEmailList.vue
layouts/default.vue
migrations/20190527115705_subjects.js
pages/emailList.vue
pages/subjects.vue
seeds/subjects.js
server/controllers/subjects/Create.js
server/controllers/subjects/Update.js
test/server/controllers/subjects.spec.js
test/server/models/subjects.spec.js

Segundo @ianCamposs, não há mais a necessidade de códigos.
@Jamadhar

CRUD de matérias necessário para futuras modificações

---

components/searchInput.vue
layouts/default.vue
pages/formingStudents.vue
server/controllers/students/List.js
server/controllers/students/UpdateAcademicHighlight.js
server/controllers/students/index.js
server/router.js
test/server/controllers/students.spec.js

Meta 8:  Gerar de forma prática o destaque acadêmico.

---

components/studentComboBox.vue

Corrige bug em que o cd não era salvo no banco de dados

---

server/controllers/documents/Upload.js
server/controllers/students/Update.js
server/utils.js
test/server/utils.spec.js

Meta 04: Gerenciar status dos alunos graduandos #130

---

components/modalPrescribedList.vue
components/studentComboBox.vue
pages/formingStudents.vue

A lista gerada no modal leva em consideração alunos que tem o atributo "prescribed=1" no banco de dados.

Meta 10: Gerar lista de alunos presentes na lista de prescrição #132

---

components/datepicker.vue
components/timepicker.vue
layouts/defaultTeacher.vue
middleware/auth.js
middleware/course.js
migrations/20190623214136_defenses.js
pages/login.vue
pages/teacher/home.vue
pages/teacher/registerPresentation.vue
server/controllers/defenses/Create.js
server/controllers/defenses/index.js
server/models/Defense.js
server/router.js
test/server/controllers/defenses.spec.js
test/server/models/defense.spec.js

Meta 21 (Utilizado pelo Professor): Gerar dados do TCC utilizando formulário.

---

components/datepicker.vue
components/defenseForm.vue
components/studentComboBox.vue
components/tccDefenseSearch.vue
components/timepicker.vue
layouts/default.vue
migrations/20190623214136_defenses.js
pages/tccDefense.vue
pages/teacher/registerPresentation.vue
server/controllers/defenses/Create.js
server/controllers/defenses/List.js
server/controllers/defenses/Update.js
server/controllers/defenses/index.js
server/router.js
test/server/controllers/defenses.spec.js

M22 lakshamana front

---

README.md
package.json

Facilita na criação do banco e diminui o número de passos para fazer o projeto funcionar.

Cria comando makedb

---

server/controllers/defenses/List.js
server/router.js
test/server/controllers/defenses.spec.js

Garantir que o professor tenha acesso a defesas que são apenas as suas

---

server/controllers/users/Update.js
server/controllers/users/index.js
server/router.js
test/server/controllers/users.spec.js

issue: #223 
[API: Recurso Usuários](https://github.com/projeto-spider/labes-2019/wiki/API:--Recurso-Usu%C3%A1rios);
[API: Recurso Usuários](https://github.com/projeto-spider/labes-2019/wiki/API:--Recurso-Usu%C3%A1rios)

Adiciona rota para Atualização de Usuários

---

components/StudentComboBox.vue
server/controllers/students/FromCsv.js
server/utils.js
test/server/utils.spec.js

Graduandos não podem ter pendências

---

pages/login.vue

 Formulário de login aceita enter mesmo estando no checkbox

---

server/controllers/documents/Delete.js
server/models/Student.js
server/utils.js
test/server/controllers/students.spec.js
test/use-seeds-data/students.js

Confirma que mudanças de apto~não apto acontecem.

---

components/SearchInput.vue
components/StudentComboBox.vue
front/students/service.js
pages/formingStudents.vue

Front agora envia CD, recarregar as listas quando move e refatoração dos parametros do search input

---

components/AsideBar.vue
layouts/default.vue

Fix navbars

---

components/DatePicker.vue
components/DefenseForm.vue
components/TccDefenseSearch.vue
layouts/defaultTeacher.vue
pages/tccDefense.vue
pages/teacher/home.vue

Adiciona o componente tccDefense onde o é possível visualizar (professor e adm) e editar (adm) os dados dos TCC.
Closes #208
Closes #194
Closes #209

Página de acompanhamento de defesas do professor

---

components/AsideBar.vue
components/InputValidation.vue
pages/signup.vue

Fix Página de cadastro de usuários

---

layouts/error.vue

Adiciona página de erro

---

package-lock.json
package.json
server/controllers/documents/Delete.js
server/controllers/documents/Upload.js
server/controllers/documents/View.js
test/server/controllers/documents.spec.js

fix #244 
No npm run test deu uns erros. Mas sinceramente, bati cabeça e não saí do lugar. Mandei para ver se é no meu PC que está bugado e ver se consigo alguma ajuda.

Muda funções síncronas para assíncronas

---

components/EmailListCompare.vue
components/ModalPrescribedList.vue
components/SearchInput.vue
components/StudentComboBox.vue
front/students/service.js

closes #243 
closes #234 
closes #168 
closes #250
closes #251
closes #181 
closes #253

Ajustes front

---

components/AsideBar.vue

Conserta AsideBar

---

components/AsideBar.vue

Trocar "Matérias" por "Componentes Curriculares" na sidebar 

---

components/AsideBar.vue
components/ModalPrescribedList.vue
pages/formingStudents.vue

Mover botão da Lista de Prescrição para a sidebar

---

pages/formingStudents.vue

Ao selecionar o destaque acadêmico + confirmar se o usuário quer selecionar o destaque acadêmico.
echance 
Closes #252

Desabilitar botão de Eleger Destaque Acadêmico 

---

front/defenses/service.js

fix defensas não mudam de status

---

components/DefenseForm.vue
components/TccDefenseSearch.vue
front/defenses/service.js
pages/teacher/registerPresentation.vue
server/controllers/defenses/TccGenerate.js
server/models/tccdocs/certificado.js
server/models/tccdocs/credenciamento.js
test/server/controllers/defenses.spec.js

Visualização de PDFs

---

server/controllers/users/Update.js
test/server/controllers/users.spec.js

Permite atualização do nome do usuário e

---

components/AsideBar.vue
components/TccDefenseSearch.vue

Tornar data do modelo de divulgação por extenso

---

server/utils.js
test/server/controllers/students.spec.js
test/server/utils.spec.js

Implementa o backend de #287 e #289

Garante que não tem como fugir de missingCollation

---

components/DefenseForm.vue

Tirar o "cancelar" do combo box de defesa.

---

server/controllers/students/EmailChanges.js
server/controllers/students/UpdateMailingList.js
test/server/controllers/students.spec.js

Relacionados:
Pr: #266 
Issue #254

Atualização nas rotas de listas de emails

---

components/StudentComboBox.vue
layouts/default.vue
layouts/defaultTeacher.vue
migrations/20190426155412_users.js
server/controllers/users/Create.js
server/controllers/users/Update.js
test/server/controllers/users.spec.js
test/server/models/user.spec.js
test/use-seeds-data/users.js

Closes #278
Closes #293 
Importante já ter pra quando precisarem colocar na parte de edição

Adiciona campo fullName nos usuários

---

server/controllers/users/List.js
test/server/controllers/users.spec.js

Relacionado:
PR #294 e issue: #224

Permite filtro de usuários por username

---

components/DefenseForm.vue
components/TccDefenseSearch.vue

Professores não podem ver documentos no combo box da defesa

---

components/SearchInput.vue
pages/formingStudents.vue

Mover botão "Eleger Destaque Acadêmico"

---

server/controllers/students/Update.js
test/server/controllers/students.spec.js

`term` só em formandos, graduandos e concluintes

---

components/AsideBar.vue
components/UserForm.vue
front/users/service.js
layouts/defaultTeacher.vue
pages/UpdateUser.vue
pages/index.vue
pages/signup.vue
pages/teacher/updateUser.vue
store/auth.js

Pagina de atualizar cadastro

---

components/EmailListCompare.vue
components/EmailListComponent.vue
front/students/service.js

**Não fazer merge antes do backend.**
Fixes: #254.
Relacionado: #184

Fix página de mudanças de mailing list

---

components/SearchInput.vue
components/StudentComboBox.vue
front/students/service.js

Adiciona campo de falta à colação de grau

---

pages/login.vue

Imagem na pagina de login 

---

server/controllers/users/List.js
test/server/controllers/users.spec.js

Listar usuários ignorando a paginação

---

components/DefenseForm.vue

Refatoração do formulário de TCC

---

components/AdmissionForm.vue
front/solicitations/service.js
layouts/admissionLayout.vue
migrations/20190524215233_solicitations.js
server/controllers/solicitations/Create.js
test/server/controllers/solicitations.spec.js
test/use-seeds-data/solicitations.js

closes #186
@Jamadhar mudei o back. Adicionei 2 campos no formulário. Conversei com o @lubien e ele me falou para colocar como texto mesmo o conteúdo dos dois inputs (curso; forma de ingresso). Ele me pediu para te avisar.

Adição do input de curso e forma de ingresso para o front-end e back-end

---

migrations/20190623214136_defenses.js
server/controllers/defenses/Create.js
server/controllers/defenses/Update.js
server/models/Defense.js
test/server/controllers/defenses.spec.js
test/server/models/defense.spec.js

Adiciona `*IsTeacher` para a banca

---

server/controllers/defenses/Delete.js
server/controllers/defenses/index.js
server/router.js
test/server/controllers/defenses.spec.js

Somente para defesas não realizadas, é claro.
Representa o backend de #274
Closes #319

Adiciona rota de deletar defesa

---

components/TccDefenseSearch.vue
layouts/admissionLayout.vue
pages/teacher/home.vue

Fix defesas TCC e atualiza CSS do formulário de admissão

---

components/StudentComboBox.vue
components/StudentComboBox/DocumentRow.vue

- Ajeita a notificação de arquivos grandes no combobox
- ajeita o .sync no componente DocumentRow
- ajeita atualização de quantidade de pendencias
closes #246

Ajustes em combobox e DocumentRow

---

migrations/20190706153229_settings.js
server/Setting.js
server/controllers/settings/List.js
server/controllers/settings/Show.js
server/controllers/settings/Update.js
server/controllers/settings/index.js
server/models/Setting.js
server/router.js
test/server/controllers/settings.spec.js
test/server/models/setting.spec.js

Relacionado a: #282 
Necessária para: #322

Cria a API de Settings

---

components/UserForm.vue
front/users/service.js
store/auth.js

Adiciona fullName para atualizar e criar usuário.

---

components/SearchInput.vue
components/StudentComboBox.vue
front/students/service.js
pages/concludingStudents.vue

Meta 13: As listas do sistema devem ser separadas por períodos(ex: 2018.2).

---

components/DefenseForm.vue
components/TccDefenseSearch.vue
front/defenses/service.js
pages/teacher/home.vue

Criação de um checkbox para saber se é professor ou não. 

---

components/UserForm.vue

Atualizar o usuário não limpa o formulário

---

server/controllers/defenses/TccGenerate.js
server/controllers/students/AttendanceRegister.js
server/controllers/students/ConcludingCertificate.js
server/utils.js

Adiciona Prof(a) aos professores

---

components/DefenseForm.vue
components/StudentComboBox.vue
components/TccDefenseSearch.vue
front/defenses/service.js
pages/teacher/registerPresentation.vue

Melhoras no modal e formulário de defesa

---

pages/formingStudents.vue

Tratar notificações desnecessárias no modal de Gerar destaque acadêmico.

---

pages/teacher/updateUser.vue

fix layout de professor

---

components/DatePicker.vue
components/DefenseForm.vue
components/TccDefenseSearch.vue
components/TimePicker.vue

Closes #334
Com participação especial de @urielfcampos

Não modificar a defesa até salvar

---

test/front/login.spec.js

Fix tests front

---

server/models/tccdocs/listaFrequencia.js

Consertos cosméticos na lista de frequência + índice do aluno + truncamento de nomes grandes.
Closes #337

Atualizações no modelo de PDF da Lista de Frequência.

---

components/SearchInput.vue
pages/formingStudents.vue
pages/index.vue

com participação especial de @lubien  
closes #59

Cria Pagina Inicial e condicional para certificado 

---

components/ImportStudents.vue
layouts/default.vue

Força recarregamento de páginas após import de alunos 

---

components/SearchInput.vue

Alterar cor do destaque academico, porem faltou colação

---

components/AdmissionForm.vue
layouts/admissionLayout.vue
pages/index.vue

fix bug do background do formulário + retirada de campos desnecessários para concluintes

---

server/utils.js

Ao atualizar o CSV, alunos graduandos aptos são resetados para graduandos não aptos

---

server/controllers/defenses/Update.js
server/router.js
test/server/controllers/defenses.spec.js

Professor pode atualizar defesas pendentes

---

components/AdmissionForm.vue

Também retira campo de matrícula no formulário para admissão de concluintes.
Closes: #363

Refatora componente de validação para usar InputValidation

---

migrations/20190623214136_defenses.js
server/controllers/defenses/TccGenerate.js
test/server/controllers/defenses.spec.js

Parte do backend
Relacionado: #369

Nota da defesa poderá ser EXC, BOM, REG e INS.

---

components/DefenseForm.vue
components/TccDefenseSearch.vue
layouts/error.vue
pages/teacher/home.vue

Closes: #354,
Closes: #366,
Closes: #369.

Corrige lentidão de DefenseForm e corrige autorizações de professor para edição defesas
